### ISSUE TITLE
Send/receive rasters

### ISSUE THREAD

**Issue by KatKatKateryna** [specklesystems/speckle-arcgis#14]

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/speckle-arcgis/pull/24

**Comment by fraguada** [comment]
@KatKatKateryna is this a 2.10 issue?

**Comment by KatKatKateryna** [comment]
> @KatKatKateryna is this a 2.10 issue?

Yes, resolved

**Comment by KatKatKateryna** [comment]
> @KatKatKateryna is this a 2.10 issue?

It was resolved in 2.9
